#!/bin/sh

#set HK_ROOT in bashrc
if [ -z "$HK_ROOT" ]; then
    echo export HK_ROOT=/homeworks >> $HOME/.bashrc
    HK_ROOT=/homeworks
fi

#set PATH in bashrc
if [ $PATH != *$HK_ROOT/codes/public/system/sbin* ]
then
    echo export PATH=\$HK_ROOT/codes/public/system/sbin:\$PATH >> $HOME/.bashrc
fi

# homeworks directories
sudo mkdir -p $HK_ROOT/projects
sudo mkdir -p $HK_ROOT/codes/public
sudo mkdir -p $HK_ROOT/codes/private
sudo chmod 775 $HK_ROOT/codes/public #A modifier, present pour le hk-code-release
sudo chmod 775 $HK_ROOT/projects
sudo chown -R $USER $HK_ROOT/projects
sudo cp -rv python system tools $HK_ROOT/codes/public

# user directories
sudo mkdir -p $HK_ROOT/users/$USER
sudo chmod 775 $HK_ROOT/users/$USER
sudo chown -R $USER $HK_ROOT/users/$USER
mkdir -p $HK_ROOT/users/$USER/projects

if [ $1 == "-d" ] 
	then
	# For developers
	mkdir -p $HK_ROOT/users/$USER/codes/private
	mkdir -p $HK_ROOT/users/$USER/codes/public
	sudo chown -R $USER $HK_ROOT/users/$USER/codes
	cp -rv `pwd`/* .git $HK_ROOT/users/$USER/codes/public
fi

exit
