# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'breakdown.ui'
#
# Created: Sun Jul 13 16:34:49 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(864, 560)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayoutMain = QtGui.QVBoxLayout()
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.horizontalLayoutTitle = QtGui.QHBoxLayout()
        self.horizontalLayoutTitle.setObjectName("horizontalLayoutTitle")
        self.labelTitle = QtGui.QLabel(self.centralwidget)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayoutTitle.addWidget(self.labelTitle)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutTitle)
        self.lineTitle = QtGui.QFrame(self.centralwidget)
        self.lineTitle.setFrameShape(QtGui.QFrame.HLine)
        self.lineTitle.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineTitle.setObjectName("lineTitle")
        self.verticalLayoutMain.addWidget(self.lineTitle)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayoutAsset = QtGui.QVBoxLayout()
        self.verticalLayoutAsset.setObjectName("verticalLayoutAsset")
        self.horizontalLayoutAssetFilter = QtGui.QHBoxLayout()
        self.horizontalLayoutAssetFilter.setObjectName("horizontalLayoutAssetFilter")
        self.labelAssetSearch = QtGui.QLabel(self.centralwidget)
        self.labelAssetSearch.setObjectName("labelAssetSearch")
        self.horizontalLayoutAssetFilter.addWidget(self.labelAssetSearch)
        self.lineEditAssetSearch = QtGui.QLineEdit(self.centralwidget)
        self.lineEditAssetSearch.setObjectName("lineEditAssetSearch")
        self.horizontalLayoutAssetFilter.addWidget(self.lineEditAssetSearch)
        self.comboBoxAssetType = QtGui.QComboBox(self.centralwidget)
        self.comboBoxAssetType.setObjectName("comboBoxAssetType")
        self.horizontalLayoutAssetFilter.addWidget(self.comboBoxAssetType)
        self.pushButtonAssetRefresh = QtGui.QPushButton(self.centralwidget)
        self.pushButtonAssetRefresh.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButtonAssetRefresh.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonAssetRefresh.setObjectName("pushButtonAssetRefresh")
        self.horizontalLayoutAssetFilter.addWidget(self.pushButtonAssetRefresh)
        self.verticalLayoutAsset.addLayout(self.horizontalLayoutAssetFilter)
        self.treeWidgetAsset = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidgetAsset.setDragEnabled(True)
        self.treeWidgetAsset.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.treeWidgetAsset.setAlternatingRowColors(True)
        self.treeWidgetAsset.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.treeWidgetAsset.setRootIsDecorated(False)
        self.treeWidgetAsset.setItemsExpandable(False)
        self.treeWidgetAsset.setAnimated(True)
        self.treeWidgetAsset.setObjectName("treeWidgetAsset")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidgetAsset)
        self.verticalLayoutAsset.addWidget(self.treeWidgetAsset)
        self.horizontalLayout.addLayout(self.verticalLayoutAsset)
        self.lineAssetPackShot = QtGui.QFrame(self.centralwidget)
        self.lineAssetPackShot.setFrameShape(QtGui.QFrame.VLine)
        self.lineAssetPackShot.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineAssetPackShot.setObjectName("lineAssetPackShot")
        self.horizontalLayout.addWidget(self.lineAssetPackShot)
        self.verticalLayoutPackShot = QtGui.QVBoxLayout()
        self.verticalLayoutPackShot.setObjectName("verticalLayoutPackShot")
        self.horizontalLayoutPackFilter = QtGui.QHBoxLayout()
        self.horizontalLayoutPackFilter.setObjectName("horizontalLayoutPackFilter")
        self.labelPackFilter = QtGui.QLabel(self.centralwidget)
        self.labelPackFilter.setObjectName("labelPackFilter")
        self.horizontalLayoutPackFilter.addWidget(self.labelPackFilter)
        self.lineEditPackFilter = QtGui.QLineEdit(self.centralwidget)
        self.lineEditPackFilter.setObjectName("lineEditPackFilter")
        self.horizontalLayoutPackFilter.addWidget(self.lineEditPackFilter)
        self.verticalLayoutPackShot.addLayout(self.horizontalLayoutPackFilter)
        self.horizontalLayoutPackBar = QtGui.QHBoxLayout()
        self.horizontalLayoutPackBar.setObjectName("horizontalLayoutPackBar")
        self.pushButtonPackAssign = QtGui.QPushButton(self.centralwidget)
        self.pushButtonPackAssign.setMinimumSize(QtCore.QSize(16, 16))
        self.pushButtonPackAssign.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonPackAssign.setObjectName("pushButtonPackAssign")
        self.horizontalLayoutPackBar.addWidget(self.pushButtonPackAssign)
        self.pushButtonPackAdd = QtGui.QPushButton(self.centralwidget)
        self.pushButtonPackAdd.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonPackAdd.setObjectName("pushButtonPackAdd")
        self.horizontalLayoutPackBar.addWidget(self.pushButtonPackAdd)
        self.pushButtonPackDisable = QtGui.QPushButton(self.centralwidget)
        self.pushButtonPackDisable.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonPackDisable.setObjectName("pushButtonPackDisable")
        self.horizontalLayoutPackBar.addWidget(self.pushButtonPackDisable)
        self.pushButtonPackSettings = QtGui.QPushButton(self.centralwidget)
        self.pushButtonPackSettings.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonPackSettings.setObjectName("pushButtonPackSettings")
        self.horizontalLayoutPackBar.addWidget(self.pushButtonPackSettings)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutPackBar.addItem(spacerItem)
        self.verticalLayoutPackShot.addLayout(self.horizontalLayoutPackBar)
        self.treeWidgetPack = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidgetPack.setDragEnabled(True)
        self.treeWidgetPack.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.treeWidgetPack.setAlternatingRowColors(True)
        self.treeWidgetPack.setSelectionMode(QtGui.QAbstractItemView.ContiguousSelection)
        self.treeWidgetPack.setRootIsDecorated(False)
        self.treeWidgetPack.setAnimated(True)
        self.treeWidgetPack.setObjectName("treeWidgetPack")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidgetPack)
        self.verticalLayoutPackShot.addWidget(self.treeWidgetPack)
        self.linePackShot = QtGui.QFrame(self.centralwidget)
        self.linePackShot.setFrameShape(QtGui.QFrame.HLine)
        self.linePackShot.setFrameShadow(QtGui.QFrame.Sunken)
        self.linePackShot.setObjectName("linePackShot")
        self.verticalLayoutPackShot.addWidget(self.linePackShot)
        self.horizontalLayoutShotFilter = QtGui.QHBoxLayout()
        self.horizontalLayoutShotFilter.setObjectName("horizontalLayoutShotFilter")
        self.labelShotFilter = QtGui.QLabel(self.centralwidget)
        self.labelShotFilter.setObjectName("labelShotFilter")
        self.horizontalLayoutShotFilter.addWidget(self.labelShotFilter)
        self.lineEditShotFilter = QtGui.QLineEdit(self.centralwidget)
        self.lineEditShotFilter.setObjectName("lineEditShotFilter")
        self.horizontalLayoutShotFilter.addWidget(self.lineEditShotFilter)
        self.verticalLayoutPackShot.addLayout(self.horizontalLayoutShotFilter)
        self.horizontalLayoutShotBar = QtGui.QHBoxLayout()
        self.horizontalLayoutShotBar.setObjectName("horizontalLayoutShotBar")
        self.pushButtonShotAssign = QtGui.QPushButton(self.centralwidget)
        self.pushButtonShotAssign.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonShotAssign.setObjectName("pushButtonShotAssign")
        self.horizontalLayoutShotBar.addWidget(self.pushButtonShotAssign)
        self.pushButtonShotRemove = QtGui.QPushButton(self.centralwidget)
        self.pushButtonShotRemove.setMaximumSize(QtCore.QSize(16, 16))
        self.pushButtonShotRemove.setObjectName("pushButtonShotRemove")
        self.horizontalLayoutShotBar.addWidget(self.pushButtonShotRemove)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutShotBar.addItem(spacerItem1)
        self.verticalLayoutPackShot.addLayout(self.horizontalLayoutShotBar)
        self.treeWidgetShot = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidgetShot.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.treeWidgetShot.setAlternatingRowColors(True)
        self.treeWidgetShot.setRootIsDecorated(False)
        self.treeWidgetShot.setAnimated(True)
        self.treeWidgetShot.setObjectName("treeWidgetShot")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidgetShot)
        self.verticalLayoutPackShot.addWidget(self.treeWidgetShot)
        self.horizontalLayout.addLayout(self.verticalLayoutPackShot)
        self.verticalLayoutMain.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayoutMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditAssetSearch, self.treeWidgetAsset)
        MainWindow.setTabOrder(self.treeWidgetAsset, self.lineEditPackFilter)
        MainWindow.setTabOrder(self.lineEditPackFilter, self.treeWidgetPack)
        MainWindow.setTabOrder(self.treeWidgetPack, self.treeWidgetShot)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTitle.setText(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAssetSearch.setText(QtGui.QApplication.translate("MainWindow", "searchAssets", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAssetRefresh.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetAsset.setSortingEnabled(True)
        self.treeWidgetAsset.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidgetAsset.isSortingEnabled()
        self.treeWidgetAsset.setSortingEnabled(False)
        self.treeWidgetAsset.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "asset", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetAsset.setSortingEnabled(__sortingEnabled)
        self.labelPackFilter.setText(QtGui.QApplication.translate("MainWindow", "searchPacks", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPackAssign.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPackAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPackDisable.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPackSettings.setText(QtGui.QApplication.translate("MainWindow", "settings", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetPack.setSortingEnabled(True)
        self.treeWidgetPack.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Packs", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidgetPack.isSortingEnabled()
        self.treeWidgetPack.setSortingEnabled(False)
        self.treeWidgetPack.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "pack", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetPack.setSortingEnabled(__sortingEnabled)
        self.labelShotFilter.setText(QtGui.QApplication.translate("MainWindow", "searchShots", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonShotAssign.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonShotRemove.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetShot.setSortingEnabled(True)
        self.treeWidgetShot.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Shots", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidgetShot.isSortingEnabled()
        self.treeWidgetShot.setSortingEnabled(False)
        self.treeWidgetShot.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "shot", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetShot.setSortingEnabled(__sortingEnabled)

