# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'font_col.ui'
#
# Created: Mon Feb  4 00:14:02 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(644, 545)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_main = QtGui.QVBoxLayout()
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.horizontalLayout_center = QtGui.QHBoxLayout()
        self.horizontalLayout_center.setObjectName("horizontalLayout_center")
        self.verticalLayout_file = QtGui.QVBoxLayout()
        self.verticalLayout_file.setObjectName("verticalLayout_file")
        self.label_proj = QtGui.QLabel(Form)
        self.label_proj.setObjectName("label_proj")
        self.verticalLayout_file.addWidget(self.label_proj)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtGui.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.label_search = QtGui.QLabel(Form)
        self.label_search.setMaximumSize(QtCore.QSize(16, 16))
        self.label_search.setObjectName("label_search")
        self.horizontalLayout.addWidget(self.label_search)
        self.lineEdit_file = QtGui.QLineEdit(Form)
        self.lineEdit_file.setObjectName("lineEdit_file")
        self.horizontalLayout.addWidget(self.lineEdit_file)
        self.verticalLayout_file.addLayout(self.horizontalLayout)
        self.listWidget_file = QtGui.QListWidget(Form)
        self.listWidget_file.setMinimumSize(QtCore.QSize(300, 0))
        self.listWidget_file.setObjectName("listWidget_file")
        brush = QtGui.QBrush(QtGui.QColor(206, 48, 48))
        brush.setStyle(QtCore.Qt.NoBrush)
        QtGui.QListWidgetItem(self.listWidget_file)
        Unnamed.setForeground(brush)
        self.verticalLayout_file.addWidget(self.listWidget_file)
        self.horizontalLayout_center.addLayout(self.verticalLayout_file)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_comments = QtGui.QLabel(Form)
        self.label_comments.setAlignment(QtCore.Qt.AlignCenter)
        self.label_comments.setObjectName("label_comments")
        self.verticalLayout.addWidget(self.label_comments)
        self.plainTextEdit_comments = QtGui.QPlainTextEdit(Form)
        self.plainTextEdit_comments.setMinimumSize(QtCore.QSize(300, 0))
        self.plainTextEdit_comments.setObjectName("plainTextEdit_comments")
        self.verticalLayout.addWidget(self.plainTextEdit_comments)
        self.horizontalLayout_center.addLayout(self.verticalLayout)
        self.verticalLayout_main.addLayout(self.horizontalLayout_center)
        self.horizontalLayout_bottom = QtGui.QHBoxLayout()
        self.horizontalLayout_bottom.setObjectName("horizontalLayout_bottom")
        self.progressBar = QtGui.QProgressBar(Form)
        self.progressBar.setMinimumSize(QtCore.QSize(550, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_bottom.addWidget(self.progressBar)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_bottom.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(Form)
        self.pushButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_bottom.addWidget(self.pushButton)
        self.verticalLayout_main.addLayout(self.horizontalLayout_bottom)
        self.labelStatus = QtGui.QLabel(Form)
        self.labelStatus.setText("")
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout_main.addWidget(self.labelStatus)
        self.verticalLayout_2.addLayout(self.verticalLayout_main)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Asset Push", None, QtGui.QApplication.UnicodeUTF8))
        self.label_proj.setText(QtGui.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Push Asset :</span><span style=\" font-size:12pt;\"> Project name</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Form", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_search.setText(QtGui.QApplication.translate("Form", "search", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_file.setSortingEnabled(True)
        __sortingEnabled = self.listWidget_file.isSortingEnabled()
        self.listWidget_file.setSortingEnabled(False)
        self.listWidget_file.item(0).setText(QtGui.QApplication.translate("Form", "sdsd", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_file.setSortingEnabled(__sortingEnabled)
        self.label_comments.setText(QtGui.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Description</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "Push", None, QtGui.QApplication.UnicodeUTF8))

