# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asset_manager_0-2-0.ui'
#
# Created: Fri Jun 20 22:40:07 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 878)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayoutMain = QtGui.QVBoxLayout()
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.horizontalLayoutTitle = QtGui.QHBoxLayout()
        self.horizontalLayoutTitle.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayoutTitle.setObjectName("horizontalLayoutTitle")
        self.labelSystemTitle = QtGui.QLabel(self.centralwidget)
        self.labelSystemTitle.setMaximumSize(QtCore.QSize(21, 16777215))
        self.labelSystemTitle.setObjectName("labelSystemTitle")
        self.horizontalLayoutTitle.addWidget(self.labelSystemTitle)
        self.labelProjectTitle = QtGui.QLabel(self.centralwidget)
        self.labelProjectTitle.setObjectName("labelProjectTitle")
        self.horizontalLayoutTitle.addWidget(self.labelProjectTitle)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutTitle)
        self.line1Main = QtGui.QFrame(self.centralwidget)
        self.line1Main.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1Main.setLineWidth(2)
        self.line1Main.setFrameShape(QtGui.QFrame.HLine)
        self.line1Main.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1Main.setObjectName("line1Main")
        self.verticalLayoutMain.addWidget(self.line1Main)
        self.horizontalLayoutCore = QtGui.QHBoxLayout()
        self.horizontalLayoutCore.setObjectName("horizontalLayoutCore")
        self.verticalLayoutLeft = QtGui.QVBoxLayout()
        self.verticalLayoutLeft.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayoutLeft.setObjectName("verticalLayoutLeft")
        self.horizontalLayoutFilter = QtGui.QHBoxLayout()
        self.horizontalLayoutFilter.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayoutFilter.setObjectName("horizontalLayoutFilter")
        self.labelFilter = QtGui.QLabel(self.centralwidget)
        self.labelFilter.setEnabled(True)
        self.labelFilter.setMaximumSize(QtCore.QSize(16, 16))
        self.labelFilter.setObjectName("labelFilter")
        self.horizontalLayoutFilter.addWidget(self.labelFilter)
        self.comboBoxAssetTypeFilter = QtGui.QComboBox(self.centralwidget)
        self.comboBoxAssetTypeFilter.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxAssetTypeFilter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBoxAssetTypeFilter.setAccessibleName("")
        self.comboBoxAssetTypeFilter.setObjectName("comboBoxAssetTypeFilter")
        self.comboBoxAssetTypeFilter.addItem("")
        self.comboBoxAssetTypeFilter.addItem("")
        self.comboBoxAssetTypeFilter.addItem("")
        self.horizontalLayoutFilter.addWidget(self.comboBoxAssetTypeFilter)
        self.comboBoxAssetTaskFilter = QtGui.QComboBox(self.centralwidget)
        self.comboBoxAssetTaskFilter.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxAssetTaskFilter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBoxAssetTaskFilter.setAccessibleName("")
        self.comboBoxAssetTaskFilter.setObjectName("comboBoxAssetTaskFilter")
        self.comboBoxAssetTaskFilter.addItem("")
        self.horizontalLayoutFilter.addWidget(self.comboBoxAssetTaskFilter)
        self.verticalLayoutLeft.addLayout(self.horizontalLayoutFilter)
        self.horizontalLayoutSearch = QtGui.QHBoxLayout()
        self.horizontalLayoutSearch.setContentsMargins(3, -1, 3, -1)
        self.horizontalLayoutSearch.setObjectName("horizontalLayoutSearch")
        self.labelSearch = QtGui.QLabel(self.centralwidget)
        self.labelSearch.setMaximumSize(QtCore.QSize(16, 16))
        self.labelSearch.setObjectName("labelSearch")
        self.horizontalLayoutSearch.addWidget(self.labelSearch)
        self.lineEditSearch = QtGui.QLineEdit(self.centralwidget)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.horizontalLayoutSearch.addWidget(self.lineEditSearch)
        self.verticalLayoutLeft.addLayout(self.horizontalLayoutSearch)
        self.horizontalLayoutExplorer = QtGui.QHBoxLayout()
        self.horizontalLayoutExplorer.setObjectName("horizontalLayoutExplorer")
        self.verticalLayoutToolBar = QtGui.QVBoxLayout()
        self.verticalLayoutToolBar.setObjectName("verticalLayoutToolBar")
        self.buttonCreateAssetToolBar = QtGui.QPushButton(self.centralwidget)
        self.buttonCreateAssetToolBar.setMinimumSize(QtCore.QSize(24, 24))
        self.buttonCreateAssetToolBar.setMaximumSize(QtCore.QSize(24, 24))
        self.buttonCreateAssetToolBar.setToolTip("")
        self.buttonCreateAssetToolBar.setObjectName("buttonCreateAssetToolBar")
        self.verticalLayoutToolBar.addWidget(self.buttonCreateAssetToolBar)
        self.buttonCreateTaskToolBar = QtGui.QPushButton(self.centralwidget)
        self.buttonCreateTaskToolBar.setMinimumSize(QtCore.QSize(24, 24))
        self.buttonCreateTaskToolBar.setMaximumSize(QtCore.QSize(24, 24))
        self.buttonCreateTaskToolBar.setToolTip("")
        self.buttonCreateTaskToolBar.setObjectName("buttonCreateTaskToolBar")
        self.verticalLayoutToolBar.addWidget(self.buttonCreateTaskToolBar)
        self.buttonExportToolBar = QtGui.QPushButton(self.centralwidget)
        self.buttonExportToolBar.setMinimumSize(QtCore.QSize(24, 24))
        self.buttonExportToolBar.setMaximumSize(QtCore.QSize(24, 24))
        self.buttonExportToolBar.setToolTip("")
        self.buttonExportToolBar.setObjectName("buttonExportToolBar")
        self.verticalLayoutToolBar.addWidget(self.buttonExportToolBar)
        self.buttonImportToolBar = QtGui.QPushButton(self.centralwidget)
        self.buttonImportToolBar.setMinimumSize(QtCore.QSize(24, 24))
        self.buttonImportToolBar.setMaximumSize(QtCore.QSize(24, 24))
        self.buttonImportToolBar.setToolTip("")
        self.buttonImportToolBar.setObjectName("buttonImportToolBar")
        self.verticalLayoutToolBar.addWidget(self.buttonImportToolBar)
        self.buttonSetStatusToolBar = QtGui.QPushButton(self.centralwidget)
        self.buttonSetStatusToolBar.setMaximumSize(QtCore.QSize(24, 24))
        self.buttonSetStatusToolBar.setToolTip("")
        self.buttonSetStatusToolBar.setObjectName("buttonSetStatusToolBar")
        self.verticalLayoutToolBar.addWidget(self.buttonSetStatusToolBar)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayoutToolBar.addItem(spacerItem)
        self.horizontalLayoutExplorer.addLayout(self.verticalLayoutToolBar)
        self.verticalLayoutTree = QtGui.QVBoxLayout()
        self.verticalLayoutTree.setObjectName("verticalLayoutTree")
        self.horizontalLayoutVersions = QtGui.QHBoxLayout()
        self.horizontalLayoutVersions.setObjectName("horizontalLayoutVersions")
        self.comboBoxVersionType = QtGui.QComboBox(self.centralwidget)
        self.comboBoxVersionType.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBoxVersionType.setAccessibleName("")
        self.comboBoxVersionType.setObjectName("comboBoxVersionType")
        self.comboBoxVersionType.addItem("")
        self.comboBoxVersionType.addItem("")
        self.horizontalLayoutVersions.addWidget(self.comboBoxVersionType)
        self.comboBoxVersions = QtGui.QComboBox(self.centralwidget)
        self.comboBoxVersions.setMaximumSize(QtCore.QSize(70, 16777215))
        self.comboBoxVersions.setAccessibleName("")
        self.comboBoxVersions.setObjectName("comboBoxVersions")
        self.comboBoxVersions.addItem("")
        self.horizontalLayoutVersions.addWidget(self.comboBoxVersions)
        self.checkBoxActive = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxActive.setEnabled(True)
        self.checkBoxActive.setChecked(True)
        self.checkBoxActive.setTristate(False)
        self.checkBoxActive.setObjectName("checkBoxActive")
        self.horizontalLayoutVersions.addWidget(self.checkBoxActive)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayoutVersions.addItem(spacerItem1)
        self.buttonRefresh = QtGui.QPushButton(self.centralwidget)
        self.buttonRefresh.setMinimumSize(QtCore.QSize(24, 24))
        self.buttonRefresh.setMaximumSize(QtCore.QSize(24, 24))
        self.buttonRefresh.setToolTip("")
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.horizontalLayoutVersions.addWidget(self.buttonRefresh)
        self.verticalLayoutTree.addLayout(self.horizontalLayoutVersions)
        self.treeWidgetMain = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidgetMain.setAlternatingRowColors(True)
        self.treeWidgetMain.setRootIsDecorated(True)
        self.treeWidgetMain.setAnimated(True)
        self.treeWidgetMain.setWordWrap(False)
        self.treeWidgetMain.setObjectName("treeWidgetMain")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidgetMain)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setBackground(0, brush)
        brush = QtGui.QBrush(QtGui.QColor(1, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item_0.setForeground(0, brush)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        font = QtGui.QFont()
        font.setItalic(True)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        font = QtGui.QFont()
        font.setItalic(True)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        font = QtGui.QFont()
        font.setItalic(True)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.treeWidgetMain.header().setVisible(False)
        self.verticalLayoutTree.addWidget(self.treeWidgetMain)
        self.horizontalLayoutExplorer.addLayout(self.verticalLayoutTree)
        self.verticalLayoutLeft.addLayout(self.horizontalLayoutExplorer)
        self.horizontalLayoutCore.addLayout(self.verticalLayoutLeft)
        self.lineCore = QtGui.QFrame(self.centralwidget)
        self.lineCore.setLineWidth(2)
        self.lineCore.setMidLineWidth(0)
        self.lineCore.setFrameShape(QtGui.QFrame.VLine)
        self.lineCore.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineCore.setObjectName("lineCore")
        self.horizontalLayoutCore.addWidget(self.lineCore)
        self.verticalLayoutInfos = QtGui.QVBoxLayout()
        self.verticalLayoutInfos.setObjectName("verticalLayoutInfos")
        self.labelImageInfos = QtGui.QLabel(self.centralwidget)
        self.labelImageInfos.setMinimumSize(QtCore.QSize(300, 300))
        self.labelImageInfos.setText("")
        self.labelImageInfos.setObjectName("labelImageInfos")
        self.verticalLayoutInfos.addWidget(self.labelImageInfos)
        self.lineInfos = QtGui.QFrame(self.centralwidget)
        self.lineInfos.setFrameShape(QtGui.QFrame.HLine)
        self.lineInfos.setFrameShadow(QtGui.QFrame.Sunken)
        self.lineInfos.setObjectName("lineInfos")
        self.verticalLayoutInfos.addWidget(self.lineInfos)
        self.plainTextEditInfos = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEditInfos.setEnabled(False)
        self.plainTextEditInfos.setPlainText("")
        self.plainTextEditInfos.setObjectName("plainTextEditInfos")
        self.verticalLayoutInfos.addWidget(self.plainTextEditInfos)
        self.horizontalLayoutCore.addLayout(self.verticalLayoutInfos)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutCore)
        self.line2Main = QtGui.QFrame(self.centralwidget)
        self.line2Main.setFrameShape(QtGui.QFrame.HLine)
        self.line2Main.setFrameShadow(QtGui.QFrame.Sunken)
        self.line2Main.setObjectName("line2Main")
        self.verticalLayoutMain.addWidget(self.line2Main)
        self.horizontalLayoutStatus = QtGui.QHBoxLayout()
        self.horizontalLayoutStatus.setObjectName("horizontalLayoutStatus")
        self.progressBarStatus = QtGui.QProgressBar(self.centralwidget)
        self.progressBarStatus.setEnabled(True)
        self.progressBarStatus.setProperty("value", 0)
        self.progressBarStatus.setObjectName("progressBarStatus")
        self.horizontalLayoutStatus.addWidget(self.progressBarStatus)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutStatus)
        self.horizontalLayout_2.addLayout(self.verticalLayoutMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSystemTitle.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelProjectTitle.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Project</span><span style=\" font-size:12pt;\"/><span style=\" font-size:12pt; font-weight:600;\">:</span><span style=\" font-size:12pt;\"> Project name</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFilter.setText(QtGui.QApplication.translate("MainWindow", "filter", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxAssetTypeFilter.setItemText(0, QtGui.QApplication.translate("MainWindow", "environment", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxAssetTypeFilter.setItemText(1, QtGui.QApplication.translate("MainWindow", "character", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxAssetTypeFilter.setItemText(2, QtGui.QApplication.translate("MainWindow", "prop", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxAssetTaskFilter.setItemText(0, QtGui.QApplication.translate("MainWindow", "model", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSearch.setText(QtGui.QApplication.translate("MainWindow", "search", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCreateAssetToolBar.setText(QtGui.QApplication.translate("MainWindow", "CA", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCreateTaskToolBar.setText(QtGui.QApplication.translate("MainWindow", "CT", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonExportToolBar.setText(QtGui.QApplication.translate("MainWindow", "EX", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonImportToolBar.setText(QtGui.QApplication.translate("MainWindow", "IM", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSetStatusToolBar.setText(QtGui.QApplication.translate("MainWindow", "SS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxVersionType.setItemText(0, QtGui.QApplication.translate("MainWindow", "trial", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxVersionType.setItemText(1, QtGui.QApplication.translate("MainWindow", "stock", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxVersions.setItemText(0, QtGui.QApplication.translate("MainWindow", "0001", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxActive.setText(QtGui.QApplication.translate("MainWindow", "active only", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRefresh.setText(QtGui.QApplication.translate("MainWindow", "RF", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMain.setSortingEnabled(True)
        self.treeWidgetMain.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "asset", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidgetMain.isSortingEnabled()
        self.treeWidgetMain.setSortingEnabled(False)
        self.treeWidgetMain.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "mickey", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMain.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "texture", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMain.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "surface", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMain.topLevelItem(0).child(1).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "v003", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMain.topLevelItem(0).child(1).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "v002", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMain.topLevelItem(0).child(1).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "v001", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMain.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "rig", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMain.topLevelItem(0).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "model", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetMain.setSortingEnabled(__sortingEnabled)

