# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asset_task_2.ui'
#
# Created: Wed Jan 16 00:48:25 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(972, 806)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_top = QtGui.QHBoxLayout()
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.label_asset_type = QtGui.QLabel(self.centralwidget)
        self.label_asset_type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_asset_type.setObjectName("label_asset_type")
        self.horizontalLayout_top.addWidget(self.label_asset_type)
        self.label_asset = QtGui.QLabel(self.centralwidget)
        self.label_asset.setAlignment(QtCore.Qt.AlignCenter)
        self.label_asset.setObjectName("label_asset")
        self.horizontalLayout_top.addWidget(self.label_asset)
        self.label_task_type = QtGui.QLabel(self.centralwidget)
        self.label_task_type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task_type.setObjectName("label_task_type")
        self.horizontalLayout_top.addWidget(self.label_task_type)
        self.label_task = QtGui.QLabel(self.centralwidget)
        self.label_task.setAlignment(QtCore.Qt.AlignCenter)
        self.label_task.setObjectName("label_task")
        self.horizontalLayout_top.addWidget(self.label_task)
        self.verticalLayout.addLayout(self.horizontalLayout_top)
        self.horizontalLayout_selector = QtGui.QHBoxLayout()
        self.horizontalLayout_selector.setObjectName("horizontalLayout_selector")
        self.verticalLayout_assetType = QtGui.QVBoxLayout()
        self.verticalLayout_assetType.setObjectName("verticalLayout_assetType")
        self.lineEdit_asset_type = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_asset_type.setObjectName("lineEdit_asset_type")
        self.verticalLayout_assetType.addWidget(self.lineEdit_asset_type)
        self.listView_asset_type = QtGui.QListView(self.centralwidget)
        self.listView_asset_type.setObjectName("listView_asset_type")
        self.verticalLayout_assetType.addWidget(self.listView_asset_type)
        self.horizontalLayout_selector.addLayout(self.verticalLayout_assetType)
        self.verticalLayout_asset = QtGui.QVBoxLayout()
        self.verticalLayout_asset.setObjectName("verticalLayout_asset")
        self.lineEdit_asset = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_asset.setObjectName("lineEdit_asset")
        self.verticalLayout_asset.addWidget(self.lineEdit_asset)
        self.listWidget_asset = QtGui.QListWidget(self.centralwidget)
        self.listWidget_asset.setObjectName("listWidget_asset")
        self.verticalLayout_asset.addWidget(self.listWidget_asset)
        self.horizontalLayout_selector.addLayout(self.verticalLayout_asset)
        self.verticalLayout_taskType = QtGui.QVBoxLayout()
        self.verticalLayout_taskType.setObjectName("verticalLayout_taskType")
        self.lineEdit_task_type = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_task_type.setObjectName("lineEdit_task_type")
        self.verticalLayout_taskType.addWidget(self.lineEdit_task_type)
        self.listView_task_type = QtGui.QListView(self.centralwidget)
        self.listView_task_type.setObjectName("listView_task_type")
        self.verticalLayout_taskType.addWidget(self.listView_task_type)
        self.horizontalLayout_selector.addLayout(self.verticalLayout_taskType)
        self.verticalLayout_task = QtGui.QVBoxLayout()
        self.verticalLayout_task.setObjectName("verticalLayout_task")
        self.lineEdit_task = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_task.setObjectName("lineEdit_task")
        self.verticalLayout_task.addWidget(self.lineEdit_task)
        self.listView_task = QtGui.QListView(self.centralwidget)
        self.listView_task.setObjectName("listView_task")
        self.verticalLayout_task.addWidget(self.listView_task)
        self.horizontalLayout_selector.addLayout(self.verticalLayout_task)
        self.verticalLayout.addLayout(self.horizontalLayout_selector)
        self.horizontalLayout_bottom = QtGui.QHBoxLayout()
        self.horizontalLayout_bottom.setObjectName("horizontalLayout_bottom")
        self.label_doc_id = QtGui.QLabel(self.centralwidget)
        self.label_doc_id.setObjectName("label_doc_id")
        self.horizontalLayout_bottom.addWidget(self.label_doc_id)
        self.pullButton = QtGui.QPushButton(self.centralwidget)
        self.pullButton.setObjectName("pullButton")
        self.horizontalLayout_bottom.addWidget(self.pullButton)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_bottom.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Asset manager", None, QtGui.QApplication.UnicodeUTF8))
        self.label_asset_type.setText(QtGui.QApplication.translate("MainWindow", "asset type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_asset.setText(QtGui.QApplication.translate("MainWindow", "asset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_task_type.setText(QtGui.QApplication.translate("MainWindow", "task type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_task.setText(QtGui.QApplication.translate("MainWindow", "task", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget_asset.setSortingEnabled(True)
        self.label_doc_id.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.pullButton.setText(QtGui.QApplication.translate("MainWindow", "Pull", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Push", None, QtGui.QApplication.UnicodeUTF8))

