# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'asset_viz.ui'
#
# Created: Sun Jan 20 21:14:59 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 595)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_main = QtGui.QVBoxLayout()
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_a = QtGui.QComboBox(self.centralwidget)
        self.comboBox_a.setObjectName("comboBox_a")
        self.comboBox_a.addItem("")
        self.comboBox_a.addItem("")
        self.comboBox_a.addItem("")
        self.verticalLayout.addWidget(self.comboBox_a)
        self.lineEdit_a = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.verticalLayout.addWidget(self.lineEdit_a)
        self.treeWidget_a = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidget_a.setAlternatingRowColors(True)
        self.treeWidget_a.setObjectName("treeWidget_a")
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_a)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.verticalLayout.addWidget(self.treeWidget_a)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelImage = QtGui.QLabel(self.centralwidget)
        self.labelImage.setMinimumSize(QtCore.QSize(300, 300))
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.verticalLayout_2.addWidget(self.labelImage)
        self.plainTextEdit_comment = QtGui.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_comment.setEnabled(False)
        self.plainTextEdit_comment.setPlainText("")
        self.plainTextEdit_comment.setObjectName("plainTextEdit_comment")
        self.verticalLayout_2.addWidget(self.plainTextEdit_comment)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_main.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.createButton = QtGui.QPushButton(self.centralwidget)
        self.createButton.setObjectName("createButton")
        self.horizontalLayout_3.addWidget(self.createButton)
        self.verticalLayout_main.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_a.setItemText(0, QtGui.QApplication.translate("MainWindow", "environment", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_a.setItemText(1, QtGui.QApplication.translate("MainWindow", "character", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_a.setItemText(2, QtGui.QApplication.translate("MainWindow", "prop", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_a.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "asset", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.treeWidget_a.isSortingEnabled()
        self.treeWidget_a.setSortingEnabled(False)
        self.treeWidget_a.topLevelItem(0).setText(0, QtGui.QApplication.translate("MainWindow", "mickey", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_a.topLevelItem(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "surface", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_a.topLevelItem(0).child(0).child(0).setText(0, QtGui.QApplication.translate("MainWindow", "v001", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_a.topLevelItem(0).child(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "v002", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_a.topLevelItem(0).child(0).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "v003", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_a.topLevelItem(0).child(1).setText(0, QtGui.QApplication.translate("MainWindow", "model", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_a.topLevelItem(0).child(2).setText(0, QtGui.QApplication.translate("MainWindow", "texture", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_a.topLevelItem(0).child(3).setText(0, QtGui.QApplication.translate("MainWindow", "rig", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget_a.setSortingEnabled(__sortingEnabled)
        self.createButton.setText(QtGui.QApplication.translate("MainWindow", "create", None, QtGui.QApplication.UnicodeUTF8))

