#!/bin/bash

if [ -n "$HK_ROOT" ]
	then
		if [ -z "$HK_PROJECT" ] 
			then

				project="ADMIN"

				if [ "-d" == $1 ]
					then
						devmode=true
						export HK_CODE_PATH=$HK_ROOT/users/$USER/codes/public
					else
						devmode=false
						export HK_CODE_PATH=$HK_ROOT/codes/public
				fi
				
				adenv="$HK_CODE_PATH/system/config"
				export PATH=$HK_CODE_PATH/system/bin:$PATH
				export HK_DEV_MODE=$devmode
				export HK_HOME=$HK_ROOT/users/$USER
				export HK_REPO="$HK_ROOT/projects"
				export HK_USER_REPO="$HK_HOME/projects"
				export HK_PROJECT_ENV="$adenv/$project.env"
				export PYTHONPATH=$HK_CODE_PATH/python/couchdb-python:$PYTHONPATH
				
				if [ -a $HK_PROJECT_ENV ]
				  	then
				  		export HK_PROJECT=$project
				    	bash --rcfile $HK_PROJECT_ENV
				    else
				    	echo "hk-project:project '$project' doesn't exists."
				fi

		else
				echo "hk-project:You already are in the project '$HK_PROJECT'. Please use the command 'exit' to leave the current project and try again."
		fi
else
	echo "hk-project:Bad env,'HK_ROOT' is null.Please call an system administrator."
fi
