#!/bin/bash

hdk_dir=/mnt/web/hdk

if [ -n "$HK_ROOT" ]
	
	then

		if [ -n "$HK_PROJECT" ]
			
			then

				if [ $HK_DEV_MODE == true ]

					then
						# declare paths
						modpath=$HK_PIPELINE/pipeline
						docpath=$HK_PIPELINE/build_doc
						outpath=$docpath/source
						outpath_template=$docpath/source_template
						buildpath=$docpath/build
						dochtml=$buildpath/html

						# delete source directory
						if [[ ( $outpath != "/" ) && ( -a $outpath ) ]]
							then
								rm -rfv $outpath
						fi

						# delete build directory
						if [[ ( $buildpath != "/" ) && ( -a $buildpath ) ]]
							then
								rm -rfv $buildpath
						fi
						
						# create source directory from source_template
						if [[ ( $outpath_template != "/" ) && ( -a $outpath_template ) ]]
							then
								cp -rv $outpath_template $outpath
						fi

						# create the doc
						sphinx-apidoc -f -A $USER -o $outpath $modpath
						make html

						# copy built documentation to web directory
						if [[ ( $hdk_dir != "/" ) && ( -a $hdk_dir ) && ( -a $dochtml ) ]]

							then
								dir=$hdk_dir/$HK_PIPELINE_VER
								
								if [[ ( $dir != "/" ) && ( -a $dir ) ]]
									
									then
										rm -rfv $dir
								
								fi

								cp -rv $dochtml $dir

						fi

					else
						echo "You should login a project as developer, see 'hk-project' help"
				
				fi

			else
				echo "You should login a project as developer, see 'hk-project' help"
		
		fi

	else
		echo "Bad env,'HK_ROOT' is null. Please call a system administrator."

fi
